version: "3.3"
services:
  db:
    container_name: mysql-server
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "security-db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "root"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
      # Allow entry public retrieval
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "33006:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - security-service:/var/lib/mysql
# Names our volume
volumes:
  security-service:
